import { useEffect } from "react";
import { Link } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { fetchProducts, removeProduct } from "../../redux/productSlice";
function Dashboard() {
 const dispatch = useDispatch(); const {items,loading,error} = useSelector((s)=>s.products);
 useEffect(()=>{dispatch(fetchProducts());},[dispatch]);
 const value=items.reduce((sum,p)=>sum+Number(p.price||0),0);
 const handleDelete=(product)=>{if(window.confirm(`Delete “${product.name}” from the shop?`))dispatch(removeProduct(product.id));};
 return <section className="admin-page container section-space"><div className="admin-heading"><div><span className="eyebrow">STORE MANAGEMENT</span><h1>Sweet shop dashboard</h1><p>Manage your treats, prices and availability.</p></div><Link className="pink-button" to="/admin/add">+ Add a product</Link></div><div className="stats-grid"><div className="stat-card"><span>Products listed</span><strong>{items.length}</strong><small>All shop treats</small></div><div className="stat-card"><span>In stock</span><strong>{items.filter(p=>Number(p.stock)>0).length}</strong><small>Available to order</small></div><div className="stat-card"><span>Featured items</span><strong>{items.filter(p=>p.featured).length}</strong><small>Shown on homepage</small></div><div className="stat-card"><span>Average price</span><strong>₹{items.length?Math.round(value/items.length).toLocaleString("en-IN"):0}</strong><small>Across current products</small></div></div><div className="admin-table-wrap"><div className="admin-table-title"><div><h2>Your products</h2><p>Changes are saved to JSON Server.</p></div><span>{items.length} items</span></div>{loading && <p className="p-4">Loading products…</p>}{error && <p className="error-message p-3">{error}</p>}<div className="table-responsive"><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Homepage</th><th>Actions</th></tr></thead><tbody>{items.map((p)=><tr key={p.id}><td><div className="admin-product"><img src={p.image} alt=""/><div><strong>{p.name}</strong><small>ID: {p.id}</small></div></div></td><td>{p.category}</td><td>₹{Number(p.price).toLocaleString("en-IN")}</td><td><span className={Number(p.stock)>0?"stock-pill":"stock-pill out"}>{Number(p.stock)>0?`${p.stock} in stock`:"Out of stock"}</span></td><td>{p.featured?"Featured":"Standard"}</td><td><div className="table-actions"><Link to={`/admin/edit/${p.id}`}>Edit</Link><button onClick={()=>handleDelete(p)}>Delete</button></div></td></tr>)}</tbody></table></div>{!loading&&!items.length&&<div className="empty-state"><p>No products yet. Add your first treat.</p></div>}</div></section>;
}
export default Dashboard;
