import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { createProduct, fetchProductById, fetchProducts, updateProduct } from "../../redux/productSlice";
const blank={name:"",category:"Cakes",price:"",oldPrice:"",rating:"4.8",image:"",description:"",badge:"Fresh today",stock:"10",featured:false};
function ProductForm(){
 const {id}=useParams();const editing=Boolean(id);const dispatch=useDispatch();const navigate=useNavigate();const {selected,items}=useSelector(s=>s.products);const [form,setForm]=useState(blank);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(editing){const existing=items.find(p=>String(p.id)===String(id));if(existing)setForm({...blank,...existing,price:String(existing.price),oldPrice:String(existing.oldPrice||""),stock:String(existing.stock||0)});else dispatch(fetchProductById(id));}else setForm(blank);},[id,editing,items,dispatch]);
 useEffect(()=>{if(editing&&selected&&String(selected.id)===String(id)&&!items.some(p=>String(p.id)===String(id)))setForm({...blank,...selected,price:String(selected.price),oldPrice:String(selected.oldPrice||""),stock:String(selected.stock||0)});},[selected,id,editing,items]);
 const update=(e)=>{const {name,value,type,checked}=e.target;setForm(prev=>({...prev,[name]:type==="checkbox"?checked:value}));};
 const submit=async(e)=>{e.preventDefault();setError("");setSaving(true);const payload={...form,price:Number(form.price),oldPrice:form.oldPrice?Number(form.oldPrice):null,rating:Number(form.rating)||4.8,stock:Number(form.stock)||0,featured:Boolean(form.featured)};try{if(editing)await dispatch(updateProduct({id,product:payload})).unwrap();else await dispatch(createProduct(payload)).unwrap();await dispatch(fetchProducts());navigate("/admin");}catch(err){setError(typeof err==="string"?err:err.message||"Could not save this product. Is JSON Server running?");}finally{setSaving(false);}};
 return <section className="container section-space form-page"><div className="form-back"><Link to="/admin">← Back to dashboard</Link></div><div className="form-card"><span className="eyebrow">{editing?"UPDATE YOUR MENU":"SOMETHING NEW IS BAKING"}</span><h1>{editing?"Edit product":"Add a new product"}</h1><p>Keep your shop details fresh and inviting.</p>{error&&<div className="form-error">{error}</div>}<form onSubmit={submit} className="product-form"><label>Product name<input name="name" value={form.name} onChange={update} required placeholder="e.g. Strawberry celebration cake"/></label><div className="form-row"><label>Category<select name="category" value={form.category} onChange={update}>{["Cakes","Cupcakes","Pastries","Desserts","Bakery"].map(c=><option key={c}>{c}</option>)}</select></label><label>Price (₹)<input type="number" name="price" min="1" value={form.price} onChange={update} required/></label></div><div className="form-row"><label>Original price (₹)<input type="number" name="oldPrice" min="0" value={form.oldPrice} onChange={update} placeholder="Optional"/></label><label>Stock quantity<input type="number" name="stock" min="0" value={form.stock} onChange={update} required/></label></div><label>Product image URL<input type="url" name="image" value={form.image} onChange={update} required placeholder="https://…"/></label>{form.image&&<img className="form-image-preview" src={form.image} alt="Product preview" onError={(e)=>{e.currentTarget.style.display="none";}} onLoad={(e)=>{e.currentTarget.style.display="block";}}/>}<label>Description<textarea name="description" value={form.description} onChange={update} rows="4" required placeholder="Describe the flavours, texture and little details…"/></label><label>Small badge<input name="badge" value={form.badge} onChange={update} placeholder="Bestseller, Fresh today…"/></label><label className="checkbox-label"><input type="checkbox" name="featured" checked={Boolean(form.featured)} onChange={update}/> Feature this product on the home page</label><div className="form-actions"><button className="pink-button" disabled={saving}>{saving?"Saving…":editing?"Save changes":"Add product"} ↗</button><Link className="cancel-link" to="/admin">Cancel</Link></div></form></div></section>;
}
export default ProductForm;
