import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchProducts } from "../redux/productSlice";
import ProductCard from "../components/ProductCard";
const categories = ["All treats", "Cakes", "Cupcakes", "Pastries", "Desserts", "Bakery"];
function Shop() {
  const dispatch = useDispatch(); const { items, loading, error } = useSelector((s) => s.products);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("All treats"); const [sort, setSort] = useState("featured");
  useEffect(() => { if (!items.length) dispatch(fetchProducts()); }, [dispatch, items.length]);
  const products = useMemo(() => items.filter((p) => (category === "All treats" || p.category === category) && `${p.name} ${p.category} ${p.description}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => sort === "price-low" ? a.price-b.price : sort === "price-high" ? b.price-a.price : sort === "name" ? a.name.localeCompare(b.name) : Number(b.featured)-Number(a.featured)), [items,category,search,sort]);
  return <><section className="page-hero shop-hero"><span className="eyebrow">MADE FRESH, JUST FOR YOU</span><h1>Our little <em>cake shop</em></h1><p>Find your next favourite bite.</p><div className="breadcrumb-line">Home <span>/</span> Shop</div></section><section className="container section-space shop-page"><div className="shop-toolbar"><div><span className="eyebrow">THE GOOD STUFF</span><h2>Shop our treats <span>({products.length})</span></h2></div><div className="shop-controls"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search cakes…" aria-label="Search cakes"/><select value={sort} onChange={(e) => setSort(e.target.value)} aria-label="Sort products"><option value="featured">Featured first</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name A–Z</option></select></div></div><div className="category-pills">{categories.map((item) => <button key={item} className={category === item ? "category-pill active" : "category-pill"} onClick={() => setCategory(item)}>{item}</button>)}</div>{loading ? <p className="loading-message">Bringing out the treats…</p> : error ? <p className="error-message">{error}. Start JSON Server with <code>npm run server</code>.</p> : products.length ? <div className="product-grid shop-grid">{products.map((product) => <ProductCard key={product.id} product={product}/>)}</div> : <div className="empty-state"><h3>No treats found just yet</h3><p>Try another search or category.</p><button className="pink-button" onClick={() => {setSearch("");setCategory("All treats");}}>Show all treats</button></div>}</section></>;
}
export default Shop;
